"""empty message

Revision ID: 84100236b6b7
Revises: 0bcd0a93303f
Create Date: 2025-02-07 13:38:39.259799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84100236b6b7'
down_revision: Union[str, None] = '0bcd0a93303f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pin_code', sa.Integer(), nullable=False),
    sa.Column('create_date_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('applied_date_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset')
    # ### end Alembic commands ###
