"""empty message

Revision ID: 8fa0df4e8286
Revises: 624ba01ea61a
Create Date: 2025-02-13 13:28:22.155056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa0df4e8286'
down_revision: Union[str, None] = '624ba01ea61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('New', 'Read', name='notificationsstate'), nullable=False),
    sa.Column('status', sa.Enum('Followed', 'LikedPost', 'NewComment', 'LikedComment', 'NewPost', name='notificationstatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('create_date_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delete_date_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
